name: flight_reserve_grp6
description: A flight reservation app.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8
  path_provider: ^2.0.14
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/image/bg-airplane.jpg
