// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhzOg5JG0pWePFoal1U_tvh-qouMc9Ylc',
    appId: '1:618426290742:web:06c8a8b4fb163d5ed13e97',
    messagingSenderId: '618426290742',
    projectId: 'elec3proj-8eb26',
    authDomain: 'elec3proj-8eb26.firebaseapp.com',
    storageBucket: 'elec3proj-8eb26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDw3eYA6JPw3L_2m69iT7jvRkm8xkhI9U',
    appId: '1:618426290742:android:6213b0c13076e628d13e97',
    messagingSenderId: '618426290742',
    projectId: 'elec3proj-8eb26',
    storageBucket: 'elec3proj-8eb26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCto5t_on4jY1Lq4M19J-CxM4DdNmERY70',
    appId: '1:618426290742:ios:5357ffbddbfa6084d13e97',
    messagingSenderId: '618426290742',
    projectId: 'elec3proj-8eb26',
    storageBucket: 'elec3proj-8eb26.firebasestorage.app',
    iosBundleId: 'com.example.helloWorldApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCto5t_on4jY1Lq4M19J-CxM4DdNmERY70',
    appId: '1:618426290742:ios:5357ffbddbfa6084d13e97',
    messagingSenderId: '618426290742',
    projectId: 'elec3proj-8eb26',
    storageBucket: 'elec3proj-8eb26.firebasestorage.app',
    iosBundleId: 'com.example.helloWorldApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhzOg5JG0pWePFoal1U_tvh-qouMc9Ylc',
    appId: '1:618426290742:web:04248923929ffcabd13e97',
    messagingSenderId: '618426290742',
    projectId: 'elec3proj-8eb26',
    authDomain: 'elec3proj-8eb26.firebaseapp.com',
    storageBucket: 'elec3proj-8eb26.firebasestorage.app',
  );
}
